# Generated by Django 5.0.1 on 2024-06-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_path',
            field=models.FileField(default='', upload_to='static/img-products'),
        ),
    ]
